version: '3'
services:
  app:
    command: npm run build && npm run start:prod
    restart: always
    environment:
      - NODE_ENV=prod
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"       
    volumes:
      - ./db-data:/var/lib/postgresql/data